import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {useCurrentTime} from 'hooks/useCurrentTime';
import {useEffect, useState} from 'react';
import {invoke} from '@tauri-apps/api/tauri';

interface Quote {
    time: string;
    time_string: string;
    quote: string;
    title: string;
    author: string;
}

export default function Home() {
    const currentTime = useCurrentTime();
    const [rawQuote, setQuote] = useState<Quote | null>(null);

    useEffect(() => {
        if (!rawQuote || (!!rawQuote && rawQuote.time !== currentTime)) {
            invoke<Quote>('get_time', {time: currentTime})
                .then((q) => {
                    setQuote(q);
                })
                .catch(console.error);
        }
    }, [rawQuote, currentTime]);

    const [before, after] = rawQuote?.quote.split(rawQuote?.time_string) ?? [];


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/src/public/favicon.ico'/>
            </Head>
            <main>
                <p>{currentTime}</p>
                <pre>{JSON.stringify(rawQuote, null, 4)}</pre>
                <p>{before} <em>{rawQuote?.time_string}</em> {after}</p>
            </main>
        </div>
    );
}
