import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { invoke } from '@tauri-apps/api/tauri'
import {useEffect, useState} from "react";

export default function Home() {

  const [name, setName] = useState('');
  const [greeting, setGreeting] = useState('');


  function greet() {
    invoke<string>('greet', { name })
        .then(g => setGreeting(g))
        .catch(console.error)
  }

  useEffect(() => {
      invoke<any>('get_time', { time: '00:00'})
          .then(console.log)
          .catch(console.error);
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/public/favicon.ico" />
      </Head>

      <div className="box">
          <div className="name">
              <input
                  type="text"
                  className="name-input"
                  value={name}
                  onChange={e => {
                      e.preventDefault();
                      setName(e.currentTarget.value);
                  }}
                  placeholder="Please enter your name..."
              />
              <button onClick={greet}>Greet!</button>
          </div>
          <div className="greeting">
              {greeting && <p>{greeting}</p>}
          </div>
      </div>
    </div>
  )
}
