import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useCurrentTime } from 'hooks/useCurrentTime';
import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/tauri';
import { DBQuote, Quote } from 'components/Quote';

export default function Home() {
    const currentTime = useCurrentTime();
    const [rawQuote, setQuote] = useState<DBQuote | null>(null);

    useEffect(() => {
        if (!rawQuote || (!!rawQuote && rawQuote.time !== currentTime)) {
            invoke<DBQuote>('get_time', { time: currentTime })
                .then((q) => {
                    setQuote(q);
                })
                .catch(console.error);
        }
    }, [rawQuote, currentTime]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/src/public/favicon.ico" />
            </Head>
            {rawQuote && <Quote {...rawQuote} />}
        </div>
    );
}
